<project xmlns="http://maven.apache.org/POM/4.0.0">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>tribefire.extension.process</groupId>
		<artifactId>parent</artifactId>
		<version>[1.0,1.1)</version>
	</parent>
	<artifactId>process-rx-module</artifactId>
	<version>1.0.4</version>
	<dependencies>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>reflex-module-api</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>access-module-api</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>cluster-module-api</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>hiconic.platform.reflex</groupId>
			<artifactId>worker-module-api</artifactId>
			<version>${V.hiconic.platform.reflex}</version>
		</dependency>
		<dependency>
			<groupId>tribefire.extension.process</groupId>
			<artifactId>process-rx-module-api</artifactId>
			<version>${V.tribefire.extension.process}</version>
		</dependency>
		<dependency>
			<groupId>tribefire.extension.process</groupId>
			<artifactId>process-rx-processing</artifactId>
			<version>${V.tribefire.extension.process}</version>
		</dependency>
		<dependency>
			<groupId>tribefire.extension.process</groupId>
			<artifactId>process-api-model</artifactId>
			<version>${V.tribefire.extension.process}</version>
		</dependency>
	</dependencies>
</project>
