// ============================================================================
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ============================================================================
/**
 * 
 * Copyright by Braintribe Technologies 
 * autogenerated code 
 *
 */

package tribefire.extension.process.model.deployment;

import com.braintribe.model.descriptive.HasDescription;
import com.braintribe.model.descriptive.HasLocalizedName;
import com.braintribe.model.generic.annotation.Abstract;
import com.braintribe.model.generic.reflection.EntityType;
import com.braintribe.model.generic.reflection.EntityTypes;

@Abstract
public interface ProcessElement extends HasErrorNode, HasDescription, HasLocalizedName {

	EntityType<ProcessElement> T = EntityTypes.T(ProcessElement.class);
}
