<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>tribefire.extension.process</groupId><artifactId>parent</artifactId><version>[1.0,1.1)</version></parent>
    <artifactId>process-rx-processing</artifactId><version>1.0.5</version>
    <dependencies>
        <dependency><groupId>tribefire.extension.process</groupId><artifactId>process-rx-module-api</artifactId><version>${V.tribefire.extension.process}</version></dependency>
        <dependency><groupId>tribefire.extension.process</groupId><artifactId>process-api</artifactId><version>${V.tribefire.extension.process}</version></dependency>
        <dependency><groupId>tribefire.extension.process</groupId><artifactId>process-data-model</artifactId><version>${V.tribefire.extension.process}</version></dependency>
        <dependency><groupId>tribefire.extension.process</groupId><artifactId>process-api-model</artifactId><version>${V.tribefire.extension.process}</version><?tag asset ?></dependency>
        <dependency><groupId>tribefire.extension.process</groupId><artifactId>process-reason-model</artifactId><version>${V.tribefire.extension.process}</version><?tag asset ?></dependency>
        <dependency><groupId>com.braintribe.gm</groupId><artifactId>worker-api</artifactId><version>${V.com.braintribe.gm}</version></dependency>
        <dependency><groupId>com.braintribe.gm</groupId><artifactId>query-model-processing</artifactId><version>${V.com.braintribe.gm}</version></dependency>
        <dependency><groupId>com.braintribe.gm</groupId><artifactId>record-model</artifactId><version>${V.com.braintribe.gm}</version><?tag asset ?></dependency>
        <dependency><groupId>com.braintribe.gm</groupId><artifactId>time-model-processing</artifactId><version>${V.com.braintribe.gm}</version></dependency>
        <dependency><groupId>com.braintribe.gm</groupId><artifactId>access-request-api</artifactId><version>${V.com.braintribe.gm}</version></dependency>
        <dependency><groupId>com.braintribe.gm</groupId><artifactId>gm-messaging-api</artifactId><version>${V.com.braintribe.gm}</version></dependency>
        <dependency><groupId>com.braintribe.gm</groupId><artifactId>gm-locking-api</artifactId><version>${V.com.braintribe.gm}</version></dependency>
        <dependency><groupId>com.braintribe.common</groupId><artifactId>ioc-annotations</artifactId><version>${V.com.braintribe.common}</version></dependency>
        <dependency><groupId>com.braintribe.common</groupId><artifactId>concurrency-api</artifactId><version>${V.com.braintribe.common}</version></dependency>
    </dependencies>
</project>
